### ISSUE TITLE
uTox segfault if you remove a contact with del key and context menu at the same time

### ISSUE THREAD

**Issue by towlie** [notsecure/uTox#249]
```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 1804.0x11b4]
0x00000000004078a2 in contextmenu_list_onselect (i=0 '\000') at ./list.c:496
496     ./list.c: No such file or directory.
(gdb) bt
#0  0x00000000004078a2 in contextmenu_list_onselect (i=0 '\000')
    at ./list.c:496
#1  0x0000000000401c27 in contextmenu_mup () at ./contextmenu.c:86
#2  0x00000000004269bc in panel_mup (p=0x568440 <panel_main>) at ./ui.c:1022
#3  0x0000000000410340 in WindowProc (hwn=0x310682, msg=514, wParam=0,
    lParam=24379552) at ./win32/main.c:1433
#4  0x0000000077b29bd1 in USER32!TranslateMessageEx ()
   from C:\Windows\system32\user32.dll
#5  0x0000000077b298da in USER32!TranslateMessage ()
   from C:\Windows\system32\user32.dll
#6  0x000000000040f6b6 in WinMain (hInstance=0x400000, hPrevInstance=0x0,
    cmd=0x1063332 "", nCmdShow=1) at ./win32/main.c:1143
#7  0x0000000000564449 in main (flags=<optimized out>,
    cmdline=<optimized out>, inst=<optimized out>)
    at ../../mingw-w64-crt/crt/crt0_c.c:18
#8  0x00000000004013b5 in __tmainCRTStartup ()
    at ../../mingw-w64-crt/crt/crtexe.c:332
#9  0x00000000004014c8 in WinMainCRTStartup ()
    at ../../mingw-w64-crt/crt/crtexe.c:184
(gdb) l
491     in ./list.c
(gdb) bt full
#0  0x00000000004078a2 in contextmenu_list_onselect (i=0 '\000')
    at ./list.c:496
No locals.
#1  0x0000000000401c27 in contextmenu_mup () at ./contextmenu.c:86
        b = 0x5b6040 <context_menu>
#2  0x00000000004269bc in panel_mup (p=0x568440 <panel_main>) at ./ui.c:1022
        draw = false
        pp = 0x568428 <__compound_literal.8+104>
        subp = 0x0
#3  0x0000000000410340 in WindowProc (hwn=0x310682, msg=514, wParam=0,
    lParam=24379552) at ./win32/main.c:1433
        mx = 160
        my = 372
#4  0x0000000077b29bd1 in USER32!TranslateMessageEx ()
   from C:\Windows\system32\user32.dll
No symbol table info available.
#5  0x0000000077b298da in USER32!TranslateMessage ()
   from C:\Windows\system32\user32.dll
No symbol table info available.
#6  0x000000000040f6b6 in WinMain (hInstance=0x400000, hPrevInstance=0x0,
    cmd=0x1063332 "", nCmdShow=1) at ./win32/main.c:1143
        msg = {hwnd = 0x310682, message = 514, wParam = 0, lParam = 24379552,
          time = 1863541, pt = {x = 909, y = 738}}
        classname = L"uTox"
---Type <return> to continue, or q <return> to quit---
        popupclassname = L"uToxgrab"
        myicon = 0x1906c3
        wc = {style = 40, lpfnWndProc = 0x40f77c <WindowProc>,
          cbClsExtra = 0, cbWndExtra = 0, hInstance = 0x400000,
          hIcon = 0x1906c3, hCursor = 0x0, hbrBackground = 0x0,
          lpszMenuName = 0x0, lpszClassName = 0x22fdd0 L"uTox"}
        wc2 = {style = 0, lpfnWndProc = 0x40e1f4 <GrabProc>, cbClsExtra = 0,
          cbWndExtra = 0, hInstance = 0x400000, hIcon = 0x1906c3,
          hCursor = 0x0, hbrBackground = 0x0, lpszMenuName = 0x0,
          lpszClassName = 0x22fdb0 L"uToxgrab"}
        nid = {cbSize = 520, hWnd = 0x310682, uID = 0, uFlags = 7,
          uCallbackMessage = 32768, hIcon = 0x1906c3,
          szTip = "Tox - tooltip", '\000' <repeats 114 times>, dwState = 0,
          dwStateMask = 0, szInfo = '\000' <repeats 255 times>, {
            uTimeout = 0, uVersion = 0},
          szInfoTitle = '\000' <repeats 63 times>, dwInfoFlags = 0,
          guidItem = {Data1 = 0, Data2 = 0, Data3 = 0,
            Data4 = "\000\000\000\000\000\000\000"}}
        save = 0x2fdee0
        langid = 7 '\a'
#7  0x0000000000564449 in main (flags=<optimized out>,
    cmdline=<optimized out>, inst=<optimized out>)
    at ../../mingw-w64-crt/crt/crt0_c.c:18
No locals.
---Type <return> to continue, or q <return> to quit---
#8  0x00000000004013b5 in __tmainCRTStartup ()
    at ../../mingw-w64-crt/crt/crtexe.c:332
        lock_free = <optimized out>
        fiberid = <optimized out>
        nested = <optimized out>
        lpszCommandLine = <optimized out>
        StartupInfo = {cb = 104, lpReserved = 0x10a3db0 "",
          lpDesktop = 0x10a3dd0 "Winsta0\\Default",
          lpTitle = 0x10a6de0 "C:\\Users\\xxx\\Desktop\\debug.exe", dwX = 0,
          dwY = 0, dwXSize = 0, dwYSize = 0, dwXCountChars = 0,
          dwYCountChars = 0, dwFillAttribute = 0, dwFlags = 1025,
          wShowWindow = 1, cbReserved2 = 0, lpReserved2 = 0x0,
          hStdInput = 0x0, hStdOutput = 0x10001, hStdError = 0x0}
        inDoubleQuote = <optimized out>
#9  0x00000000004014c8 in WinMainCRTStartup ()
    at ../../mingw-w64-crt/crt/crtexe.c:184
        ret = 255
```

**Comment by GrayHatter** [comment]
@towlie is this still happening for you?

**Comment by towlie** [comment]
Seems to be fixed since pressing DEL key while context menu is open doesn't delete the context anymore. 
When did that change?

**Comment by GrayHatter** [comment]
if you really care, you can use git bisect http://git-scm.com/docs/git-bisect
