### ISSUE TITLE
Can't send text to groupchat

### ISSUE THREAD

**Issue by zetok** [notsecure/uTox#714]
I couldn't send text to groupchat. What is strange, [qTox is affected too](https://github.com/tux3/qTox/issues/940). µTox version: 0.1.8a
Text ↓
```
Core was generated by `qtox -P zetok'.                                                                                                                                        
Program terminated with signal SIGSEGV, Segmentation fault.                                                                                                                   
#0  0x00007f7bc679bc3f in pushbuf_flush (push=push@entry=0x7f7bdb2f68e0) at /var/tmp/portage/x11-libs/libdrm-2.4.52/work/libdrm-2.4.52/nouveau/pushbuf.c:425                  
425     /var/tmp/portage/x11-libs/libdrm-2.4.52/work/libdrm-2.4.52/nouveau/pushbuf.c: No such file or directory.                                                              
(gdb) bt                                                                                                                                                                      
#0  0x00007f7bc679bc3f in pushbuf_flush (push=push@entry=0x7f7bdb2f68e0) at /var/tmp/portage/x11-libs/libdrm-2.4.52/work/libdrm-2.4.52/nouveau/pushbuf.c:425                  
#1  0x00007f7bc679c836 in nouveau_pushbuf_kick (push=0x7f7bdb2f68e0, chan=<optimized out>)                                                                                    
    at /var/tmp/portage/x11-libs/libdrm-2.4.52/work/libdrm-2.4.52/nouveau/pushbuf.c:774                                                                                       
```

**Comment by GrayHatter** [comment]
@zetok can you provide a little more information on how to reproduce this?

**Comment by tsudoko** [comment]
Just try pasting the text under "Text ↓" into the groupchat.

**Comment by GrayHatter** [comment]
so, this is a tox core issue. I'm going to report it there...

interestingly, if you remove the additional spaces from the end, it does work, or if you delete any 1 line it will also work... so I think WTF applies...
